version: '3'
services:
  frontend:
    image: proj-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - inet

networks:
  inet: